In [16]:
# LAB TASK

import numpy as np

arr = np.arange(2, 11)
matrix = arr.reshape(3,3)
matrix = matrix.astype(float)

flat = matrix.reshape(-1)

print("Matrix:\n", matrix)
print("Flattened:", flat)
print("Maximum:", np.max(flat))
print("Minimum:", np.min(flat))

Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum: 10.0
Minimum: 2.0


In [18]:
# Iterating 3-D Array
d3 = np.array(np.array( [
    [[1,2,3], [4,5,6]], [7,8,9],[10,11,12]],
    [[13,14,15], [16,17,18]]))
print("The dimension of array d3 is: ",d3.ndim)
print(d3)
for x in d3:
  for y in x:
    for z in y:
      print(z)

TypeError: Field elements must be 2- or 3-tuples, got '[13, 14, 15]'

In [15]:
# Iterating 2-D

d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) # 2-D Array
print("Elements of array d1 are ",d2)
for x in d2:
  for i in x:
    print(i)

Elements of array d1 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [13]:
# Iterating 1-D Array

d1 = np.array([6,8,1,2,54,5,2])
for x in d1:
  print(x)

6
8
1
2
54
5
2


In [12]:
# NumPy Array, Copy Vs View

a = np.array([1, 2, 3, 4, 5, 6])
print("Array a", a)
b = a[:2]
print("Array b",b)
b += 1
print("Array b after increment if a", b)
print('Array a =', a, '; array b =', b)
 #Create a new array, using numpy.copy array
a = np.array([1,2,3,4])
b = a[:2].copy()
b += 1
print('a= ', a, 'b = ', b)

Array a [1 2 3 4 5 6]
Array b [1 2]
Array b after increment if a [2 3]
Array a = [2 3 3 4 5 6] ; array b = [2 3]
a=  [1 2 3 4] b =  [2 3]


In [11]:
# Flatten Array

a2D = np.array([[1, 2], [3, 4]])
print("Array a2D", a2D)
a2D.reshape(-1) # array flatten through reshape

Array a2D [[1 2]
 [3 4]]


array([1, 2, 3, 4])

In [10]:
# NumPy Array Shape

a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # Create a NumPy 2-D array
a2shape = a2.shape # Get the shape of the array
print("Shape of the array:", a2shape)

Shape of the array: (2, 4)


In [9]:
# Array slicing with step [index:index:step]
# print("Elements of array d1 are ",d1)
print("Array d1 slicing with step:d1{1:6:2] ",d1[1:6:2])

Array d1 slicing with step:d1{1:6:2]  [8 2 5]


In [8]:
# NumPy Array Slicing Practice
d1 = np.array([6,8,1,2,54,5,3]) # 1-D Array
print("Elements of array d1 are: ",d1)
print("Elements slicing 'd1[1:5]' ",d1[1:5]) # 1-D Array (The result includes the start index.excludes the end index)
print("Elements slicing 'd1[:3]' ",d1[:3]) # SLice elements from start index[0] to index[3], index[3] excluded
print("Elements slicing 'd1[:]' ",d1[3:]) # SLice elements from start index[3] to ;ast index, last index excluded
print("Elements slicing 'd1[-3:-1]' ",d1[-3:-1]) # SLice elements (negative slicing) from index[-3] to index[-1]. index[-1] excluded
d2 = np.array([[5, 9, 3, 4], [21, 65, 8, 99], [56, 98, 1, 2]]) # 2-D array
print("Elements of array d2 are ",d2)
print("Elements slicing 'd2[0,1:3]' ",d2[0,1:3]) # 2-D Array slicing : Slice elements from array[0], index[1] to index[3], index[3] excluded

Elements of array d1 are:  [ 6  8  1  2 54  5  3]
Elements slicing 'd1[1:5]'  [ 8  1  2 54]
Elements slicing 'd1[:3]'  [6 8 1]
Elements slicing 'd1[:]'  [ 2 54  5  3]
Elements slicing 'd1[-3:-1]'  [54  5]
Elements of array d2 are  [[ 5  9  3  4]
 [21 65  8 99]
 [56 98  1  2]]
Elements slicing 'd2[0,1:3]'  [9 3]


In [7]:
import numpy as np
d3array = np.array ([
    [ # Depth 0
     [1, 2, 3], # Row 0
     [4, 5, 6], # Row 1
    ],
    [   # Depth 1
        [7, 8, 9], # Row 0
        [10, 11, 12], # Row 1
    ],
    [   # Depth 2
     [13, 14, 15], # Row 0
     [16, 17, 18 ], # Row 1
    ],
])
print("The dimension of array d2array is: ",d3array.ndim)
print(d3array)
#d3array[depth_index][row_index][column_index]
item = d3array[2][0][0] # Depth 2, Row 0, Column 0
print("Item at d3array[2][0][0] is: ",d3array[2][0][0])

The dimension of array d2array is:  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Item at d3array[2][0][0] is:  13


In [6]:
d1 = np.array([1, 2, 3, 4, 5])
print("The dimensions of the array d1 is  ", d1.ndim)
print("Elements of array d1 are: ",d1)
d2 = np.array([[50, 69, 34, 45], [45,65, 68, 99], [50, 98, 1, 2]]) # 2-D array
print("Elements of array d2 are ",d2)
print("The dimension of array d2 is",d2.ndim)
print("Element at (1,0) row 1 column 0 is ",d2[1,0]) # Accessing element at index (1,0)

The dimensions of the array d1 is   1
Elements of array d1 are:  [1 2 3 4 5]
Elements of array d2 are  [[50 69 34 45]
 [45 65 68 99]
 [50 98  1  2]]
The dimension of array d2 is 2
Element at (1,0) row 1 column 0 is  45


In [5]:
# Creating a 1-D array by passing a list into NumPy's array() function.

import numpy as np
A = np.array([1, 2, 3, 4, 5])
print(A)
# Create a 2-D array by passing a list of lists into array().
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
# Create a 3-D array by passing a list of lists into array().
C = np.array([[[1, 2, 3], [4, 5, 6]], [[14, 15, 16]]])
print(C)
C_dimensions = C.ndimprint
print (C_dimensions)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [4]:
print("Type of array", type(arr))
print("Dimensions of array arr is", arr.ndim)
d0= np.array(23) # numpy 0-D array array creation
print("Dimensions of array d0 is", d0.ndim)
fruit_list = ["Apple", "Mango", "Banana"]
print(fruit_list)
print("Type of fruit list is: " , type(fruit_list))
fruit_list = np.array(fruit_list)
#print(fruit_list)
print("Type of fruit list is: " , type(fruit_list))

Type of array <class 'numpy.ndarray'>
Dimensions of array arr is 1
Dimensions of array d0 is 0
['Apple', 'Mango', 'Banana']
Type of fruit list is:  <class 'list'>
Type of fruit list is:  <class 'numpy.ndarray'>


In [1]:
# NumPy, written in C, to speed up. By default arrays are not in Python, so we use library NumPy (Numerical Python)

import numpy as np #import numpy
print("Numpy Version ", np.__version__)
arr = np.array([1, 2, 3, 4, 5])
print(arr) # numpy array creation
# Create a simple array

Numpy Version  2.0.2
[1 2 3 4 5]
