**A* Search**

A* is a path finding algorithm used in maps, games and AI.
It selects the next node using:

𝑓(𝑛)=𝑔(𝑛)+ℎ(𝑛) f(n)=g(n)+h(n)

Where:
g(n) = cost from start to current node
h(n) = estimated cost to reach goal (heuristic)

The node with lowest f value is selected first.

**Common Heuristic Methods**

1. Manhattan Distance
2. Euclidean Distance
3. Diagonal Distance
4. These help estimate distance to goal faster.

In [ ]:
# Task 2 — Implementing another A* example (Shortest Path in Graph )

import heapq # heapq is used to implement a priority queue..
# Graph represented as an adjacency list
# Each node points to its neighbors with the cost to reach them

graph = {
    'A': [('B',1), ('C',3)], # From A we can go to B with cost 1, and C with cost 3
    'B': [('D',3), ('E',6)], # From B we can go to D and E
    'C': [('F',5)], # From C we  go to F
    'D': [('G',2)], # From D go to G
    'E': [('G',1)], # From E, go to G
    'F': [('G',2)], # From F we go to G
    'G': [] # G is the goal node so it has no neighbors
}

heuristic = {
    'A':7,
    'B':6,
    'C':5,
    'D':3,
    'E':2,
    'F':2,
    'G':0 # Goal node heuristic is always 0
}

def a_star(start, goal):
    pq = [] # priority queue to store nodes to explore
    heapq.heappush(pq,(0,start))

    visited = set()

    while pq:
        cost,node = heapq.heappop(pq)

        if node == goal:
            print("Goal reached:", node)
            return

        if node not in visited:
            visited.add(node)

            for neighbor,weight in graph[node]:
                f = weight + heuristic[neighbor]
                heapq.heappush(pq,(f,neighbor))

a_star('A','G') # call A* algorithm from start node A to goal node G

Goal reached: G


In [6]:
import numpy as np

goal = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,0]])

start = np.array([[1,2,3],
                  [4,0,6],
                  [7,5,8]])

def heuristic(state):
    h = 0
    for i in range(3):
        for j in range(3):
            if state[i][j] != goal[i][j] and state[i][j] != 0:
                h += 1
    return h


def find_zero(state):
    pos = np.where(state == 0)
    return pos[0][0], pos[1][0]


def get_neighbors(state):
    neighbors = []
    x, y = find_zero(state)

    moves = [(0,1),(1,0),(0,-1),(-1,0)]

    for dx,dy in moves:
        nx, ny = x+dx, y+dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = state.copy()

            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]

            neighbors.append(new_state)

    return neighbors


def a_star(start):

    open_list = [(heuristic(start), start)]
    visited = []

    while open_list:

        open_list.sort(key=lambda x: x[0])
        cost, state = open_list.pop(0)

        print(state)
        print()

        if np.array_equal(state, goal):
            print("Goal Reached!")
            return

        visited.append(state.tolist())

        for neighbor in get_neighbors(state):
            if neighbor.tolist() not in visited:
                f = heuristic(neighbor)
                open_list.append((f, neighbor))


a_star(start)

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]

Goal Reached!


In [ ]:
# Function to evaluate number of misplaced tiles
def evaluate_misplaced(puzzle, goal):
    misplaced = 0
    visited = []

    for i in range(len(puzzle)):
        if puzzle[i] != 0 and puzzle[i] != goal[i]:
            misplaced += 1

    visited.append(puzzle)

    return misplaced, visited


# initial state
puzzle = []
puzzle.append(2)
puzzle.append(8)
puzzle.append(3)
puzzle.append(1)
puzzle.append(6)
puzzle.append(4)
puzzle.append(7)
puzzle.append(0)
puzzle.append(5)

# goal state
goal = []
goal.append(1)
goal.append(2)
goal.append(3)
goal.append(8)
goal.append(0)
goal.append(4)
goal.append(7)
goal.append(6)
goal.append(5)

state, visited = evaluate_misplaced(puzzle, goal)

print("Misplaced Tiles:", state)
print("Visited States:", visited)

Misplaced Tiles: 4
Visited States: [[2, 8, 3, 1, 6, 4, 7, 0, 5]]
